FROM continuumio/miniconda3

LABEL maintainer="Sergio Bugallo <sergiobugalloenjamio@gmail.com"

RUN pip install --no-cache-dir \
        mlflow numpy Cython scipy pandas scikit-learn boto3 cloudpickle typer loguru
